######################################################################
# Automatically generated by qmake (3.0) niedz. maj 14 21:21:17 2017
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += .
QT += widgets network
CONFIG += c++11
OBJECTS_DIR = ../obj
DESTDIR = ../bin

# Input
HEADERS += client.h
SOURCES += client.cpp
