language: cpp

sudo: required
dist: trusty

addons:
 apt:
  packages:
  - build-essential
  - qtbase5-dev
  - devscripts
  - dpkg-dev
  - debhelper
  - fakeroot

script:
- make -f make.mk debian

notifications:
 email: false
