######################################################################
# Automatically generated by qmake (3.0) sob. wrz 2 21:23:23 2017
######################################################################

TEMPLATE = app
TARGET = qtictactoe
INCLUDEPATH += include
CONFIG += c++11
QT += core network gui widgets
OBJECTS_DIR=src

SOURCES += src/*.cpp
