######################################################################
# Automatically generated by qmake (3.0) niedz. maj 14 21:21:17 2017
######################################################################

TEMPLATE = app
TARGET = server
INCLUDEPATH += .
QT += widgets network core
CONFIG += c++11
OBJECTS_DIR = ../obj
MOC_DIR = ../obj
DESTDIR = ../bin

# Input
HEADERS += server.h
SOURCES += server.cpp
