name: qtictactoe
version: 0.5.3
summary: Tic Tac Toe game in QT
description: desc

grade: stable
confinement: strict

apps:
    qtictactoe:
        command: desktop-launch qtictactoe
        desktop: usr/share/applications/qtictactoe.desktop
        plugs:
            - unity7
            - desktop
            - home
            - x11

parts:
    main:
        source: https://github.com/dawidd6/qtictactoe.git
        source-tag: 0.5.3
        plugin: make
        stage-packages:
            - libqt5gui5
        after:
            - desktop-qt5
        build-packages:
            - qtbase5-dev
            - pkg-config
